create table public.cities_buffer (
  id bigint generated by default as identity not null,
  city text null,
  region text null,
  federal text null,
  population text null,
  founded_or_first_mentioned text null,
  status text null,
  old_names text null,
  latitude text null,
  longitude text null,
  gibdd_codes text null,
  gibdd_region_id text null,
  gibdd_type text null,
  created_at timestamp with time zone null default now(),
  constraint cities_buffer_pkey primary key (id)
) TABLESPACE pg_default;

create table public.weather_buffer (
  id bigserial not null,
  time text null,
  city text null,
  temperature_2m text null,
  soil_temperature_0cm text null,
  apparent_temperature text null,
  precipitation text null,
  rain text null,
  snowfall text null,
  snow_depth text null,
  wind_speed_10m text null,
  wind_gusts_10m text null,
  wind_direction_10m text null,
  visibility text null,
  cloud_cover text null,
  is_day text null,
  weather_code text null,
  created_at timestamp with time zone null default now(),
  constraint weather_buffer_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_weather_city_time on public.weather_buffer using btree (city, "time") TABLESPACE pg_default;

create table public.gibdd_codes (
  id bigserial not null,
  city text null,
  region_id text null,
  codes text null,
  type text null,
  count integer null,
  created_at timestamp with time zone null default now(),
  constraint gibdd_codes_pkey primary key (id)
) TABLESPACE pg_default;

create table public.gibdd_dtp_buffer (
  id bigserial not null,
  city text null,
  region_id text null,
  district_id text not null,
  year text null,
  month text null,
  raw_data text null,
  created_at timestamp with time zone null default now(),
  kart_id text not null,
  constraint gibdd_dtp_buffer_pkey primary key (kart_id, district_id)
) TABLESPACE pg_default;

create index IF not exists idx_gibdd_dtp_city_year_month on public.gibdd_dtp_buffer using btree (city, year, month) TABLESPACE pg_default;

create table public.cities_clean (
  id serial not null,
  city text null,
  region text null,
  federal text null,
  population integer null,
  founded_or_first_mentioned text null,
  status text null,
  old_names text null,
  latitude numeric null,
  longitude numeric null,
  gibdd_codes text null,
  gibdd_region_id text null,
  gibdd_type text null,
  updated_at timestamp with time zone null default now(),
  constraint cities_clean_pkey primary key (id),
  constraint cities_clean_city_region_key unique (city, region)
) TABLESPACE pg_default;

create table public.weather_clean (
  id serial not null,
  city_id integer null,
  time timestamp with time zone not null,
  temperature numeric null,
  apparent_temperature numeric null,
  precipitation numeric null,
  rain numeric null,
  snowfall numeric null,
  snow_depth numeric null,
  wind_speed_10m numeric null,
  wind_gusts_10m numeric null,
  wind_direction_10m numeric null,
  cloud_cover numeric null,
  is_day numeric null,
  weather_code numeric null,
  visibility numeric null,
  soil_temperature_0cm numeric null,
  updated_at timestamp with time zone null default now(),
  time_local timestamp with time zone null,
  constraint weather_clean_pkey primary key (id),
  constraint weather_clean_city_id_time_key unique (city_id, "time"),
  constraint weather_clean_city_id_fkey foreign KEY (city_id) references cities_clean (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.gibdd_dtp_main (
  id serial not null,
  kart_id integer not null,
  district_id text not null,
  city_id integer null,
  date date null,
  time time without time zone null,
  dtp_type text null,
  fatalities integer null,
  injured integer null,
  vehicles_count integer null,
  participants_count integer null,
  emtp_number text null,
  constraint gibdd_dtp_main_pkey primary key (id),
  constraint gibdd_dtp_main_kart_id_district_id_key unique (kart_id, district_id),
  constraint gibdd_dtp_main_city_id_fkey foreign KEY (city_id) references cities_clean (id)
) TABLESPACE pg_default;

create table public.gibdd_dtp_place (
  id serial not null,
  dtp_id integer not null,
  locality text null,
  street text null,
  house text null,
  road_category text null,
  weather text[] null,
  road_condition text null,
  light text null,
  latitude numeric null,
  longitude numeric null,
  road_disadvantages text[] null,
  location_scheme text[] null,
  nearby_objects text[] null,
  constraint gibdd_dtp_place_pkey primary key (id),
  constraint gibdd_dtp_place_dtp_id_fkey foreign KEY (dtp_id) references gibdd_dtp_main (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.gibdd_vehicles (
  id serial not null,
  dtp_id integer not null,
  vehicle_number text null,
  vehicle_status text null,
  vehicle_type text null,
  brand text null,
  model text null,
  color text null,
  drive_type text null,
  year integer null,
  has_trailer text null,
  tech_condition text null,
  ownership text null,
  owner_type text null,
  constraint gibdd_vehicles_pkey primary key (id),
  constraint gibdd_vehicles_dtp_id_fkey foreign KEY (dtp_id) references gibdd_dtp_main (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.gibdd_participants_veh (
  id serial not null,
  dtp_id integer not null,
  vehicle_id integer null,
  role text null,
  condition text null,
  gender text null,
  driving_experience integer null,
  alcohol text null,
  seat_belt text null,
  leaving text null,
  participant_number text null,
  seat_group text null,
  injured_card_id text null,
  violations text[] null,
  other_violations text[] null,
  constraint gibdd_participants_veh_pkey primary key (id),
  constraint gibdd_participants_veh_dtp_id_fkey foreign KEY (dtp_id) references gibdd_dtp_main (id) on delete CASCADE,
  constraint gibdd_participants_veh_vehicle_id_fkey foreign KEY (vehicle_id) references gibdd_vehicles (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.gibdd_participants_other (
  id serial not null,
  dtp_id integer not null,
  role text null,
  condition text null,
  gender text null,
  alcohol text null,
  leaving text null,
  participant_number text null,
  violations text[] null,
  other_violations text[] null,
  constraint gibdd_participants_other_pkey primary key (id),
  constraint gibdd_participants_other_dtp_id_fkey foreign KEY (dtp_id) references gibdd_dtp_main (id) on delete CASCADE
) TABLESPACE pg_default;

CREATE TABLE gibdd_codes_buffer (
    id SERIAL PRIMARY KEY,
    city TEXT,
    gibdd_region_id TEXT,
    gibdd_codes TEXT,
    path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_gibdd_codes_buffer_city ON gibdd_codes_buffer (city);




 SELECT w.time_local AS "Время",
    EXTRACT(year FROM w.time_local)::integer AS "Год",
    EXTRACT(hour FROM w.time_local)::integer AS "Час",
    EXTRACT(month FROM w.time_local)::integer AS month_num,
        CASE EXTRACT(month FROM w.time_local)
            WHEN 1 THEN '01. Январь'::text
            WHEN 2 THEN '02. Февраль'::text
            WHEN 3 THEN '03. Март'::text
            WHEN 4 THEN '04. Апрель'::text
            WHEN 5 THEN '05. Май'::text
            WHEN 6 THEN '06. Июнь'::text
            WHEN 7 THEN '07. Июль'::text
            WHEN 8 THEN '08. Август'::text
            WHEN 9 THEN '09. Сентябрь'::text
            WHEN 10 THEN '10. Октябрь'::text
            WHEN 11 THEN '11. Ноябрь'::text
            WHEN 12 THEN '12. Декабрь'::text
            ELSE NULL::text
        END AS "Месяц",
    w.city_id,
    cc.city AS "Город",
        CASE
            WHEN w.temperature < '-10'::integer::numeric THEN '1. Мороз (< -10°C)'::text
            WHEN w.temperature >= '-10'::integer::numeric AND w.temperature <= '-3'::integer::numeric THEN '2. Холодно (-10°C до -3°C)'::text
            WHEN w.temperature >= '-3'::integer::numeric AND w.temperature <= 3::numeric THEN '3. Около нуля (-3°C до +3°C)'::text
            WHEN w.temperature >= 3::numeric AND w.temperature <= 10::numeric THEN '4. Прохладно (+3°C до +10°C)'::text
            WHEN w.temperature > 10::numeric THEN '5. Тепло (> +10°C)'::text
            ELSE NULL::text
        END AS "Температура",
        CASE
            WHEN w.snowfall > 0::numeric THEN '1. Снег'::text
            WHEN w.precipitation > 0::numeric AND w.snowfall = 0::numeric THEN '2. Дождь'::text
            ELSE '3. Нет осадков'::text
        END AS "Осадки",
        CASE
            WHEN w.wind_speed_10m < 2::numeric THEN '1. Штиль (<2 м/с)'::text
            WHEN w.wind_speed_10m >= 2::numeric AND w.wind_speed_10m <= 5::numeric THEN '2. Слабый (2-5 м/с)'::text
            WHEN w.wind_speed_10m >= 5::numeric AND w.wind_speed_10m <= 10::numeric THEN '3. Умеренный (5-10 м/с)'::text
            WHEN w.wind_speed_10m > 10::numeric THEN '4. Сильный (>10 м/с)'::text
            ELSE NULL::text
        END AS "Ветер",
        CASE
            WHEN w.cloud_cover < 20::numeric THEN '1. Ясно (<20%)'::text
            WHEN w.cloud_cover >= 20::numeric AND w.cloud_cover <= 60::numeric THEN '2. Переменная облачность (20-60%)'::text
            WHEN w.cloud_cover > 60::numeric THEN '3. Пасмурно (>60%)'::text
            ELSE NULL::text
        END AS "Облачность",
        CASE
            WHEN w.is_day = 1::numeric THEN 'День'::text
            ELSE 'Ночь'::text
        END AS "День",
        CASE
            WHEN gdm.fatalities > 0 AND gdm.injured > 0 THEN 'С погибшими и ранеными'::text
            WHEN gdm.fatalities > 0 THEN 'Только с погибшими'::text
            WHEN gdm.injured > 0 THEN 'Только с ранеными'::text
            ELSE 'Без пострадавших'::text
        END AS "Тип ДТП",
    count(DISTINCT gdm.id) AS "Количество ДТП",
    sum(gdm.fatalities) AS "Погибшие",
    sum(gdm.injured) AS "Раненые"
   FROM weather_clean w
     LEFT JOIN gibdd_dtp_main gdm ON w.city_id = gdm.city_id AND gdm.date = w.time_local::date AND EXTRACT(hour FROM gdm."time") = EXTRACT(hour FROM w.time_local)
     LEFT JOIN cities_clean cc ON w.city_id = cc.id
  GROUP BY w.time_local, w.city_id, cc.city, w.temperature, w.snowfall, w.precipitation, w.wind_speed_10m, w.cloud_cover, w.is_day, gdm.fatalities, gdm.injured;


 SELECT concat_ws(' + '::text,
        CASE
            WHEN w.temperature < '-10'::integer::numeric THEN 'Мороз (< -10°C)'::text
            WHEN w.temperature >= '-10'::integer::numeric AND w.temperature <= '-3'::integer::numeric THEN 'Холодно (-10°C до -3°C)'::text
            WHEN w.temperature >= '-3'::integer::numeric AND w.temperature <= 3::numeric THEN 'Около нуля (-3°C до +3°C)'::text
            WHEN w.temperature >= 3::numeric AND w.temperature <= 10::numeric THEN 'Прохладно (+3°C до +10°C)'::text
            WHEN w.temperature > 10::numeric THEN 'Тепло (> +10°C)'::text
            ELSE NULL::text
        END,
        CASE
            WHEN w.snowfall > 0::numeric THEN 'Снег'::text
            WHEN w.precipitation > 0::numeric AND w.snowfall = 0::numeric THEN 'Дождь'::text
            ELSE 'Нет осадков'::text
        END,
        CASE
            WHEN w.cloud_cover < 20::numeric THEN 'Ясно'::text
            WHEN w.cloud_cover >= 20::numeric AND w.cloud_cover <= 60::numeric THEN 'Переменная облачность'::text
            WHEN w.cloud_cover > 60::numeric THEN 'Пасмурно'::text
            ELSE NULL::text
        END,
        CASE
            WHEN w.wind_speed_10m < 2::numeric THEN 'Штиль'::text
            WHEN w.wind_speed_10m >= 2::numeric AND w.wind_speed_10m <= 5::numeric THEN 'Слабый ветер'::text
            WHEN w.wind_speed_10m >= 5::numeric AND w.wind_speed_10m <= 10::numeric THEN 'Умеренный ветер'::text
            WHEN w.wind_speed_10m > 10::numeric THEN 'Сильный ветер'::text
            ELSE NULL::text
        END) AS "Погодное сочетание",
    count(DISTINCT gdm.id) AS "Всего ДТП",
    count(*) AS "Всего часов",
    round(count(DISTINCT gdm.id)::numeric / count(*)::numeric, 3) AS "ДТП в час",
    sum(gdm.fatalities) AS "Всего погибших",
    round(sum(gdm.fatalities)::numeric / count(*)::numeric, 3) AS "Погибших в час"
   FROM weather_clean w
     LEFT JOIN gibdd_dtp_main gdm ON w.city_id = gdm.city_id AND gdm.date = w.time_local::date AND EXTRACT(hour FROM gdm."time") = EXTRACT(hour FROM w.time_local)
  GROUP BY (
        CASE
            WHEN w.temperature < '-10'::integer::numeric THEN 'Мороз (< -10°C)'::text
            WHEN w.temperature >= '-10'::integer::numeric AND w.temperature <= '-3'::integer::numeric THEN 'Холодно (-10°C до -3°C)'::text
            WHEN w.temperature >= '-3'::integer::numeric AND w.temperature <= 3::numeric THEN 'Около нуля (-3°C до +3°C)'::text
            WHEN w.temperature >= 3::numeric AND w.temperature <= 10::numeric THEN 'Прохладно (+3°C до +10°C)'::text
            WHEN w.temperature > 10::numeric THEN 'Тепло (> +10°C)'::text
            ELSE NULL::text
        END), (
        CASE
            WHEN w.snowfall > 0::numeric THEN 'Снег'::text
            WHEN w.precipitation > 0::numeric AND w.snowfall = 0::numeric THEN 'Дождь'::text
            ELSE 'Нет осадков'::text
        END), (
        CASE
            WHEN w.cloud_cover < 20::numeric THEN 'Ясно'::text
            WHEN w.cloud_cover >= 20::numeric AND w.cloud_cover <= 60::numeric THEN 'Переменная облачность'::text
            WHEN w.cloud_cover > 60::numeric THEN 'Пасмурно'::text
            ELSE NULL::text
        END), (
        CASE
            WHEN w.wind_speed_10m < 2::numeric THEN 'Штиль'::text
            WHEN w.wind_speed_10m >= 2::numeric AND w.wind_speed_10m <= 5::numeric THEN 'Слабый ветер'::text
            WHEN w.wind_speed_10m >= 5::numeric AND w.wind_speed_10m <= 10::numeric THEN 'Умеренный ветер'::text
            WHEN w.wind_speed_10m > 10::numeric THEN 'Сильный ветер'::text
            ELSE NULL::text
        END)
 HAVING count(DISTINCT gdm.id) > 1500
  ORDER BY (round(count(DISTINCT gdm.id)::numeric / count(*)::numeric, 3)) DESC;
